# Generated by Django 5.2 on 2025-09-28 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('organization', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('date', models.DateField()),
                ('species', models.CharField(choices=[('Avicennia', 'Avicennia (Factor: 2.5)'), ('Rhizophora', 'Rhizophora (Factor: 3.0)'), ('Sonneratia', 'Sonneratia (Factor: 2.0)')], max_length=50)),
                ('seedling_count', models.PositiveIntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('land_paper', models.FileField(upload_to='projects/land_papers/')),
                ('ngo_certificate', models.FileField(upload_to='projects/ngo_certificates/')),
                ('drone_image', models.ImageField(blank=True, null=True, upload_to='projects/drone_images/')),
                ('field_photo', models.ImageField(blank=True, null=True, upload_to='projects/field_photos/')),
                ('ipfs_cid', models.CharField(blank=True, max_length=255, null=True)),
                ('blockchain_txn', models.CharField(blank=True, max_length=255, null=True)),
                ('token_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('tokenized', 'Tokenized')], default='submitted', max_length=20)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
