# Generated by Django 5.2 on 2025-09-28 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='name',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='blockchain_txn',
            new_name='organization_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='organization',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='drone_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='field_photo',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ipfs_cid',
        ),
        migrations.RemoveField(
            model_name='project',
            name='land_paper',
        ),
        migrations.RemoveField(
            model_name='project',
            name='ngo_certificate',
        ),
        migrations.RemoveField(
            model_name='project',
            name='token_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='verification_notes',
        ),
        migrations.RemoveField(
            model_name='project',
            name='verified_by',
        ),
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='seedling_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('provisional', 'Provisional (Submitted)'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('submit', 'Submitted for Verification'), ('resubmit', 'Resubmitted after Rejection'), ('approve', 'Approved by Verifier'), ('reject', 'Rejected by Verifier'), ('upload_doc', 'Document Uploaded')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='projects.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('land_paper', 'Land Papers'), ('ngo_paper', 'NGO Certification'), ('ngo_experience', 'NGO Past Experience'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='project_docs/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='projects.project')),
            ],
        ),
    ]
